export const ACTIVE_STORAGE_ADAPTER = Symbol("ACTIVE_STORAGE_ADAPTER");
export const OBJECT_STORAGE = Symbol("OBJECT_STORAGE");
export const PUBLIC_DELIVERY = Symbol("PUBLIC_DELIVERY");
export const MALWARE_SCANNER = Symbol("MALWARE_SCANNER");
export const CDN_CACHE_INVALIDATOR = Symbol("CDN_CACHE_INVALIDATOR");
