import type { UiKitLabels } from "./ui-kit-labels";

/**
 * The English language pack: every UI kit string. Components never fall back
 * to it — an app opts in at its root (`<UiKitLanguageProvider language="en">`).
 * A new language is a sibling file satisfying `UiKitLabels`, registered in
 * `language-packs.ts`.
 */
export const UI_KIT_LABELS_EN: UiKitLabels = {
	alertDialog: {
		confirm: "Confirm",
		cancel: "Cancel",
		loading: "Working…",
		close: "Close dialog",
		typeKeywordBefore: "Type",
		typeKeywordAfter: "to confirm",
		reasonLabel: "Reason (required)",
		reasonPlaceholder: "Explain why this change is needed…",
		dontAskAgain: "Don't ask again",
	},
	analyticsRangePicker: {
		range: "Date range",
		customDays: "Days",
		pickDays: "Pick the first and last day",
		apply: "Apply",
		interval: "Group by",
	},
	appCommandPalette: {
		placeholder: "Search pages, commands, settings…",
		shortcutHint: "⌘K",
		pinnedSectionTitle: "Pinned",
		recentSectionTitle: "Recent",
		quickActionsSectionTitle: "Quick Actions",
		commandsSectionTitle: "Commands",
		pagesSectionTitle: "Pages",
		scopeLabels: { all: "", commands: "Commands", files: "Pages", settings: "Settings" },
		clearScopeAriaLabel: (scopeLabel: string): string => `Clear ${scopeLabel} scope filter`,
		expandSectionAriaLabel: (section: string): string => `Expand ${section}`,
		collapseSectionAriaLabel: (section: string): string => `Collapse ${section}`,
		pinItemAriaLabel: (title: string): string => `Pin ${title}`,
		unpinItemAriaLabel: (title: string): string => `Unpin ${title}`,
		hiddenItemsCount: (count: number): string => `${String(count)} item${count === 1 ? "" : "s"} hidden`,
		noResultsTitle: "No results found",
		noResultsHintBefore: "Try adjusting your search terms or",
		noResultsClearFilter: "clear the filter",
		noResultsHintAfter: "to browse all pages",
		noResultsForQuery: (query: string): string => `No results for “${query}”`,
		didYouMean: (title: string): string => `Did you mean “${title}”?`,
		footerNavigate: "navigate",
		footerOpen: "open",
		footerClose: "close",
		footerPrefix: "prefix",
		escapeKey: "esc",
	},
	appShellProfileDropdown: {
		openMenuAriaLabel: "Open profile menu",
		logout: "Logout",
	},
	appShellTopbarSearch: {
		mobileAriaLabel: "Search",
		desktopAriaLabel: "Search pages",
	},
	authLayout: {
		mobileBack: "Back",
		toggleThemeAria: "Toggle theme",
		rightsReserved: "All rights reserved.",
	},
	breadcrumb: {
		ariaLabel: "breadcrumb",
		ellipsis: "More",
	},
	breadcrumbTrail: {
		errorMessage: "Could not load the breadcrumb trail",
		retry: "Retry",
		copyLink: "Copy link to this page",
		copyLinkFailedTitle: "Could not copy — select the address bar manually",
		linkCopied: "Link copied",
		copyFailed: "Could not copy link",
		moreBreadcrumbsAriaLabel: "More breadcrumbs",
		showAllBreadcrumbsTitle: "Show all breadcrumbs",
	},
	carousel: {
		carouselRoleDescription: "carousel",
		slideRoleDescription: "slide",
		previousSlide: "Previous slide",
		nextSlide: "Next slide",
	},
	codeBlock: {
		copy: "Copy code",
		copied: "Copied",
		download: "Download code",
		wrap: "Wrap",
		noWrap: "No wrap",
		showMore: "Show more",
		showLess: "Show less",
		code: "Code",
		languageCode: (language: string): string => `${language} code`,
		lines: (regionLabel: string): string => `${regionLabel} lines`,
		foldLines: (from: number, to: number): string => `Fold lines ${String(from)} to ${String(to)}`,
		unfoldLines: (from: number, to: number): string => `Unfold lines ${String(from)} to ${String(to)}`,
		unfoldHiddenLines: (count: number): string => `Unfold ${String(count)} hidden lines`,
		hiddenLines: (count: number): string => `... ${String(count)} lines`,
		complete: (lineCount: number): string => `Code generation complete, ${String(lineCount)} lines.`,
	},
	combobox: {
		openOptions: "Open options",
		clearSelection: "Clear selection",
		clearAll: "Clear all",
		loading: "Loading options…",
		empty: "No results found",
		moreSelected: "More selected options",
		removeOption: (label: string): string => `Remove ${label}`,
		removeOptionFallback: "Remove option",
		selectedCount: (count: number): string => `${String(count)} selected`,
	},
	dataTable: {
		actionsMenuTitle: "Actions",
		openRowMenu: "Open row menu",
		actionsColumnHeader: "Actions",
		searchPlaceholder: "Search...",
		searchAriaLabel: "Search rows",
		clearSearchAriaLabel: "Clear search",
		noDataTitle: "No data available",
		noDataDescription: "Get started by adding your first item.",
		noResultsTitle: "No results found",
		noResultsDescription: "Try adjusting your search or filter criteria to find what you're looking for.",
		clearFilters: "Clear filters",
		selectAllAriaLabel: "Select all",
		selectRowAriaLabel: "Select row",
		selectAllPageRowsSelected: "All {pageCount} rows on this page are selected.",
		selectAllFilteredRows: "Select all {totalCount} rows",
		selectedRowCount: "1 row selected",
		selectedRowsCount: "{count} rows selected",
		allRowsSelected: "All {totalCount} rows selected",
		clearSelection: "Clear",
		deleteSelected: "Delete selected",
		mobileSelectAll: "Select all",
		export: "Export",
		exportAs: "Export as",
		exportCsv: "CSV",
		exportCsvDescription: "Comma-separated values",
		exportJson: "JSON",
		exportJsonDescription: "JavaScript object notation",
		exportPdf: "PDF",
		exportPdfDescription: "Portable document format",
		exportSpreadsheet: "Spreadsheet",
		exportSpreadsheetDescription: "Excel-compatible .xls",
		columnsToggle: "Columns",
		resultsCount: "{filtered} of {total} results",
		showingResults: "Showing {from} to {to} of {total} results",
		showPerPage: "Show",
		perPage: "per page",
		showingPageCount: "Showing {count} results",
		pageOfTotal: "Page {page} of {totalPages}",
		firstPageAriaLabel: "Go to first page",
		previousPageAriaLabel: "Go to previous page",
		nextPageAriaLabel: "Go to next page",
		lastPageAriaLabel: "Go to last page",
		goToPageAriaLabel: "Go to page {page}",
		pinColumnAriaLabel: "Pin column",
		unpinColumnAriaLabel: "Unpin column",
		exportCurrentPage: "Current page (CSV)",
		exportCurrentPageDescription: "Exports only the rows visible on this page",
		loadingTableAriaLabel: "Loading table data",
	},
	dialog: {
		close: "Close",
	},
	kpiDirection: {
		up: "Up",
		down: "Down",
		flat: "No change",
	},
	lockoutCountdown: {
		lockedPrefix: "Too many attempts — try again in",
		lockedExpired: "You can try again now.",
	},
	pagination: {
		ariaLabel: "pagination",
	},
	panelSidebarNav: {
		navigationAriaLabel: "Main navigation",
		secondaryNavigationAriaLabel: "Account",
		searchPlaceholder: "Search menu…",
		searchAriaLabel: "Search sidebar menu",
		clearSearchAriaLabel: "Clear sidebar search",
		noResultsTitle: "No matching pages",
		noResultsDescription: "Try a different search term",
		pinnedSectionTitle: "Pinned",
		moveSectionUpTitle: "Move section up (Alt+↑)",
		moveSectionDownTitle: "Move section down (Alt+↓)",
		moveSectionUpAriaLabel: (sectionTitle: string): string => `Move ${sectionTitle} section up`,
		moveSectionDownAriaLabel: (sectionTitle: string): string => `Move ${sectionTitle} section down`,
		itemUnavailableTitle: "This feature is currently unavailable",
		routeAnnouncement: (pageLabel: string): string => `Navigated to ${pageLabel}`,
	},
	passwordInput: {
		show: "Show password",
		hide: "Hide password",
		capsLockOn: "Caps Lock is on",
	},
	passwordStrengthMeter: {
		title: "Password strength",
	},
	scrollToTop: {
		label: "Scroll to top",
	},
	select: {
		clearSelection: "Clear selection",
		clearAll: "Clear all selections",
		moreSelected: "More selected options",
		removeOption: (value: string): string => `Remove ${value}`,
		loading: "Loading options…",
		empty: "No options",
		nothingSelected: "Nothing selected",
		selectedOne: (label: string): string => `Selected ${label}`,
		selectedMany: (count: number, labels: string): string => `${String(count)} selected: ${labels}`,
	},
	sheet: {
		close: "Close",
	},
	shellThemeToggle: {
		toggle: "Toggle theme",
	},
	sidebar: {
		toggleSidebar: "Toggle sidebar",
		mobileTitle: "Sidebar",
		mobileDescription: "Displays the mobile sidebar.",
	},
	timeSeriesChart: {
		partial: "partial",
		partialNote: "Shaded periods are cut off by the start or end of the range, so they cover fewer days.",
		showTable: "Show as table",
		period: "Period",
	},
	toast: {
		viewport: "Notifications",
		close: "Close toast",
		countdown: (seconds: number): string => `Dismisses in ${String(seconds)}s`,
		errorAnnouncement: "Error",
		notificationAnnouncement: "Notification",
	},
};
