/**
 * Dev utility: POST a properly HMAC-signed Resend webhook event to the
 * endpoint and print the response. Proves signature verification works.
 *
 * The webhook-id / webhook-timestamp / webhook-signature headers are
 * GENERATED by this script (it simulates what Resend would send) — you don't
 * need to source them from anywhere. The only secret involved is the signing
 * secret, which is auto-loaded from apps/api/.env (RESEND_WEBHOOK_SECRET).
 *
 * Usage (from the repo root):
 *   pnpm --filter @workspace/api exec tsx scripts/test-webhook-signature.ts
 *
 * Override via env if needed:
 *   RESEND_WEBHOOK_SECRET=whsec_xxx WEBHOOK_URL=https://... \
 *     pnpm --filter @workspace/api exec tsx scripts/test-webhook-signature.ts
 *
 * Expected: signed request → 200, tampered request → 403.
 */
import { createHmac } from "node:crypto";
import { readFileSync } from "node:fs";

/** Minimal .env reader — pulls RESEND_WEBHOOK_SECRET / WEBHOOK_URL. */
function loadEnvValue(processEnv: NodeJS.ProcessEnv, key: string): string | undefined {
	const explicit: string | undefined = processEnv[key];
	if (explicit) {
		return explicit;
	}
	try {
		const envFile = readFileSync(new URL("../.env", import.meta.url), "utf8");
		const line: string | undefined = envFile.split("\n").find((l: string): boolean => l.startsWith(`${key}=`));
		return line ? line.slice(key.length + 1).trim() : undefined;
	} catch {
		return undefined;
	}
}

const secret: string = loadEnvValue(process.env, "RESEND_WEBHOOK_SECRET") ?? "";
const url: string = loadEnvValue(process.env, "WEBHOOK_URL") ?? "http://localhost:8080/notifications/email-webhook";

if (!secret.startsWith("whsec_")) {
	throw new Error(
		"RESEND_WEBHOOK_SECRET not found. It lives in the Resend dashboard: Webhooks → your webhook → Signing secret (whsec_...). " +
			"Add it to apps/api/.env as RESEND_WEBHOOK_SECRET=whsec_... and re-run — the script now loads it automatically.",
	);
}

const msgId = `msg_test_${String(Date.now())}`;
const timestamp = String(Math.floor(Date.now() / 1000));
const payload = JSON.stringify({
	type: "email.delivered",
	data: { email_id: "e5e8d669-9ef0-44de-98f9-4097dcab36d8" },
});

// standard-webhooks scheme: base64-decode the part after "whsec_", then
// HMAC-SHA256 over "<msgId>.<timestamp>.<payload>".
const key: Buffer = Buffer.from(secret.replace(/^whsec_/, ""), "base64");
const signedContent = `${msgId}.${timestamp}.${payload}`;
const signature = createHmac("sha256", key).update(signedContent).digest("base64");

console.warn("webhook-id          →", msgId);
console.warn("webhook-timestamp   →", timestamp);
console.warn("webhook-signature   →", `v1,${String(signature)}`);
console.warn("body                →", payload);
console.warn("");
console.warn("─────────────────────────────── Swagger copy-paste block ───────────────────────────────");
console.warn("Paste these into the three header fields + the body of the 'Try it out' panel:");
console.warn("");
console.warn("Header: webhook-id          →", msgId);
console.warn("Header: webhook-timestamp   →", timestamp);
console.warn("Header: webhook-signature   →", `v1,${String(signature)}`);
console.warn("Body (paste EXACTLY, keep it on one line):");
console.warn(payload);
console.warn("");
console.warn("Or test the full tunnel in one shot (no Swagger needed):");
console.warn(
	`curl -s -X POST '${url}' -H 'content-type: application/json' ` +
		`-H 'webhook-id: ${msgId}' -H 'webhook-timestamp: ${timestamp}' ` +
		`-H 'webhook-signature: v1,${String(signature)}' -d '${payload}'`,
);
console.warn("─────────────────────────────────────────────────────────────────────────────────────────");
console.warn("");

const headers: Readonly<Record<string, string>> = {
	"content-type": "application/json",
	"webhook-id": msgId,
	"webhook-timestamp": timestamp,
	"webhook-signature": `v1,${String(signature)}`,
};
async function postOnce(targetUrl: string, body: string): Promise<string> {
	try {
		const res: Response = await fetch(targetUrl, { method: "POST", headers, body });
		const bodyText: string = await res.text();
		return `${String(res.status)} | ${bodyText}`;
	} catch (cause: unknown) {
		const detail: string = cause instanceof Error ? cause.message : String(cause);
		return `network error (is the API on :8080 / tunnel up?) — ${detail}`;
	}
}

console.warn("signed request   →", await postOnce(url, payload));

const tampered: string = JSON.stringify({
	type: "email.delivered",
	data: { email_id: "deadbeef-0000-0000-0000-000000000000" },
});
console.warn("tampered request →", await postOnce(url, tampered));
